version: "3.5"

services:
  api01: &api
    image: docker.io/library/rinha-backend-pedrovsn-01
    hostname: api01
    environment:
      - JDBC_CONNECTION=jdbc:postgresql://db:5432/rinha
      - DB_USER=admin
      - DB_PASSWORD=123
    ports:
      - "8095:8090"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8096:8090"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "32MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1