server:
  port: 8090

---
# Default
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${JDBC_CONNECTION}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

---
# Local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/rinha
    username: admin
    password: 123
    type: com.zaxxer.hikari.HikariDataSource

---

# Test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

